// <auto-generated />
using System;
using Focus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Focus.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201203332_AdicionandoMedicacoes")]
    partial class AdicionandoMedicacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Focus.Domain.Entities.Lembrete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraTomou")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TratamentoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TratamentoId");

                    b.ToTable("Lembretes");
                });

            modelBuilder.Entity("Focus.Domain.Entities.Medicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BulaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DosagemPadrao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Laboratorio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicacoes");
                });

            modelBuilder.Entity("Focus.Domain.Entities.Tratamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DosagemPersonalizada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervaloHoras")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedicacaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tratamentos");
                });

            modelBuilder.Entity("Focus.Domain.Entities.UsuarioTDAH", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Focus.Domain.Entities.Lembrete", b =>
                {
                    b.HasOne("Focus.Domain.Entities.Tratamento", "Tratamento")
                        .WithMany()
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("Focus.Domain.Entities.Tratamento", b =>
                {
                    b.HasOne("Focus.Domain.Entities.Medicacao", "Medicacao")
                        .WithMany()
                        .HasForeignKey("MedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Focus.Domain.Entities.UsuarioTDAH", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicacao");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
